### ISSUE TITLE
criproxy version

### ISSUE THREAD

**Issue by guangxuli** [Mirantis/criproxy#20]
A little confusing about that :
Is our newest criproxy backward compatible with old k8s version？
if not， I think it's better to add a flag(version) which can show/print current criproxy version obviously.

@ivan4th

**Comment by jellonek** [comment]
What do you mean by "old k8s version"? criproxy should be compatible with 1.8, 1.9, 1.10 and 1.11 versions of k8s at the moment.

**Comment by guangxuli** [comment]
sorry, I didn't make that clear, "old k8s version" means k8s version < 1.11 .
hmm, if it is compatible with 1.8, 1.9, 1.10 and 1.11 versions, there is no need to add the extra flag.
thanks.
