### ISSUE TITLE
Batch Job support

### ISSUE THREAD

**Issue by jorgesece** [Mirantis/criproxy#23]
Hi, 
I'm trying to use criproxy with kubernetes batch jobs, and it is not using my CRI. Is criproxy supporting Jobs?

Thank you

**Comment by jorgesece** [comment]
Job is ported by criproxy. I have test with kubernetes v1.11.3 and criproxy v0.12.0

**Comment by ivan4th** [comment]
Actually, jobs are completely orthogonal to CRI Proxy. CRI only deals with pods and it's kube-controller-manager's task to create pods for the jobs; and kube-controller-manager doesn't use CRI, which is only used by kubelet.
